landregistrydb:
  image: postgres:9.5
  volumes:
    - /var/dockervolumes/postgres/land_registry/9.5/data:/var/lib/postgresql/data
  expose:
    - "5432"
  container_name: landregistrydb
landregistryupdater:
  build: landregistryupdater
  container_name: landregistryupdater
  links:
    - landregistrydb
landregistrypgcharts:
  image: imiell/pgcharts
  container_name: landregistrypgcharts
  links:
    - landregistrydb
  ports:
    - "2000:9042"
# First time only, but can be run each time
  #command: /bin/bash -c '/root/pgcharts/build/bin/pgcharts setup pgsql://postgres@landregistrydb/pgcharts && /root/pgcharts/build/bin/pgcharts start && /root/pgcharts/build/bin/pgcharts register pgsql://postgres@landregistrydb/land_registry && sleep infinity'
  command: /bin/bash -c '/root/pgcharts/build/bin/pgcharts setup pgsql://postgres@landregistrydb/pgcharts && /root/pgcharts/build/bin/pgcharts start && sleep infinity'
